---
title: "Appendix - Quantitative results"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F)

```

This report provides summary information for all 33 London local authorities on:

* demography
* deprivation
* children's services
* mental health outcomes
* SEN outcomes

```{r load data, echo = F}
setwd("S:/ICH_PPP_CENB_CEBCH/Matthew/OHID/DATABASE/For GitHub")
library(data.table)
library(ggplot2)

spine <- fread("final_database/contextual_database.csv")
ftps <- fread("final_database/fingertips_data_london.csv")

ftps <- merge(ftps,
              spine[, c("LAD21C", "budget_2021_75")],
              by.x = "areacode", 
              by.y = "LAD21C",
              all.x = T)
```

# Demography
```{r child population size, echo = F, fig.width = 10, fig.height = 7.5}

spine[, LAD21NM := factor(LAD21NM,
                          levels = spine$LAD21NM[order(spine$budget_2021_75, spine$child_population_2021, decreasing = T)])]
spine[, budget_2021_75_tmp := as.character(budget_2021_75)]

namevals <- c("0", "1")
colvalues <- c("blue", "red")
labvalues <- c("No", "Yes")

names(colvalues) <- namevals
names(labvalues) <- namevals

ggplot(aes(x = LAD21NM,
           y = child_population_2021,
           fill = as.factor(budget_2021_75_tmp)),
       data = spine) +
  geom_bar(stat = "identity") +
  scale_y_continuous(name = "Child population 2021",
                     expand = c(0, 0)) +
  scale_x_discrete(name = "") +
  labs(fill = "TF2",
       title = "Child population size in 2021") +
  scale_fill_manual("TF2",
                    labels = labvalues,
                    values = colvalues) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(colour = "black",
                                   angle = 45,
                                   hjust = 1),
        axis.text.y = element_text(colour = "black")) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 1]$child_population_2021, probs = 0.50)), " (",
                                  round(quantile(spine[budget_2021_75 == 1]$child_population_2021, probs = 0.25)), ", ",
                                  round(quantile(spine[budget_2021_75 == 1]$child_population_2021, probs = 0.75)), ")"),
           x = 10, y = 75000, size = 3) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 0]$child_population_2021, probs = 0.50)), " (",
                                  round(quantile(spine[budget_2021_75 == 0]$child_population_2021, probs = 0.25)), ", ",
                                  round(quantile(spine[budget_2021_75 == 0]$child_population_2021, probs = 0.75)), ")"),
           x = 28, y = 75000, size = 3)
```

```{r percentage pop children, echo = F, fig.width = 10, fig.height = 7.5}

spine[, LAD21NM := factor(LAD21NM,
                          levels = spine$LAD21NM[order(spine$budget_2021_75, spine$perc_child_population_2021, decreasing = T)])]
spine[, budget_2021_75_tmp := as.character(budget_2021_75)]

namevals <- c("0", "1")
colvalues <- c("blue", "red")
labvalues <- c("No", "Yes")

names(colvalues) <- namevals
names(labvalues) <- namevals

ggplot(aes(x = LAD21NM,
           y = perc_child_population_2021,
           fill = as.factor(budget_2021_75_tmp)),
       data = spine) +
  geom_bar(stat = "identity") +
  scale_y_continuous(name = "% child population 2021",
                     expand = c(0, 0),
                     limits = c(0, 30)) +
  scale_x_discrete(name = "") +
  labs(fill = "TF2",
       title = "Percentage of population who are children 2021") +
  scale_fill_manual("TF2",
                    labels = labvalues,
                    values = colvalues) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(colour = "black",
                                   angle = 45,
                                   hjust = 1),
        axis.text.y = element_text(colour = "black")) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 1]$perc_child_population_2021, probs = 0.50)), " (",
                                  round(quantile(spine[budget_2021_75 == 1]$perc_child_population_2021, probs = 0.25)), ", ",
                                  round(quantile(spine[budget_2021_75 == 1]$perc_child_population_2021, probs = 0.75)), ")"),
           x = 10, y = 25, size = 3) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 0]$perc_child_population_2021, probs = 0.50)), " (",
                                  round(quantile(spine[budget_2021_75 == 0]$perc_child_population_2021, probs = 0.25)), ", ",
                                  round(quantile(spine[budget_2021_75 == 0]$perc_child_population_2021, probs = 0.75)), ")"),
           x = 28, y = 25, size = 3)
```

```{r pop change, echo = F, fig.width = 10, fig.height = 7.5}
spine[, change_child_population_pc := (change_child_population - 1) * 100]
spine[, LAD21NM := factor(LAD21NM, levels = spine$LAD21NM[order(spine$budget_2021_75, spine$change_child_population_pc, decreasing = T)])]
spine[, budget_2021_75_tmp := as.character(budget_2021_75)]

namevals <- c("0", "1")
colvalues <- c("blue", "red")
labvalues <- c("No", "Yes")

names(colvalues) <- namevals
names(labvalues) <- namevals

ggplot(aes(x = LAD21NM,
           y = change_child_population_pc,
           fill = as.factor(budget_2021_75_tmp)),
       data = spine) +
  geom_bar(stat = "identity") +
  scale_y_continuous(name = "Relative change in child population 2021 to 2021",
                     expand = c(0, 0),
                     limits = c(-20, 20)) +
  scale_x_discrete(name = "") +
  labs(fill = "TF2",
       title = "Percentage change in child population 2011 to 2021") +
  scale_fill_manual("TF2",
                    labels = labvalues,
                    values = colvalues) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(colour = "black",
                                   angle = 45,
                                   hjust = 1),
        axis.text.y = element_text(colour = "black")) +
  geom_hline(yintercept = 0, colour = "black")
```

```{r pop perc BAME, fig.width = 10, fig.height = 7.5}
spine[, LAD21NM := factor(LAD21NM, levels = spine$LAD21NM[order(spine$budget_2021_75, spine$perc_child_em_population_2021, decreasing = T)])]
spine[, budget_2021_75_tmp := as.character(budget_2021_75)]

namevals <- c("0", "1")
colvalues <- c("blue", "red")
labvalues <- c("No", "Yes")

names(colvalues) <- namevals
names(labvalues) <- namevals

ggplot(aes(x = LAD21NM,
           y = perc_child_em_population_2021,
           fill = as.factor(budget_2021_75_tmp)),
       data = spine) +
  geom_bar(stat = "identity") +
  scale_y_continuous(name = "% child population not white 2021",
                     expand = c(0, 0),
                     limits = c(0, 100)) +
  scale_x_discrete(name = "") +
  labs(fill = "TF2",
       title = "Percentage of child population who are not white 2021") +
  scale_fill_manual("TF2",
                    labels = labvalues,
                    values = colvalues) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(colour = "black",
                                   angle = 45,
                                   hjust = 1),
        axis.text.y = element_text(colour = "black")) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 1]$perc_child_em_population_2021, probs = 0.50,na.rm = T)), " (",
                                  round(quantile(spine[budget_2021_75 == 1]$perc_child_em_population_2021, probs = 0.25,na.rm = T)), ", ",
                                  round(quantile(spine[budget_2021_75 == 1]$perc_child_em_population_2021, probs = 0.75,na.rm = T)), ")"),
           x = 10, y = 80, size = 3) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 0]$perc_child_em_population_2021, probs = 0.50,na.rm = T)), " (",
                                  round(quantile(spine[budget_2021_75 == 0]$perc_child_em_population_2021, probs = 0.25,na.rm = T)), ", ",
                                  round(quantile(spine[budget_2021_75 == 0]$perc_child_em_population_2021, probs = 0.75,na.rm = T)), ")"),
           x = 28, y = 80, size = 3)
```

# Deprivation
```{r fsm, fig.width = 10, fig.height = 7.5}
spine[, LAD21NM := factor(LAD21NM, levels = spine$LAD21NM[order(spine$budget_2021_75, spine$fsm_eligible_percent_aut202021, decreasing = T)])]
spine[, budget_2021_75_tmp := as.character(budget_2021_75)]

namevals <- c("0", "1")
colvalues <- c("blue", "red")
labvalues <- c("No", "Yes")

names(colvalues) <- namevals
names(labvalues) <- namevals

ggplot(aes(x = LAD21NM,
           y = fsm_eligible_percent_aut202021,
           fill = as.factor(budget_2021_75_tmp)),
       data = spine) +
  geom_bar(stat = "identity") +
  scale_y_continuous(name = "% children getting FSM 2020/21",
                     expand = c(0, 0),
                     limits = c(0, 40)) +
  scale_x_discrete(name = "") +
  labs(fill = "2021 Family Hub budget",
       title = "Percentage of children getting free school meals in 2020/21") +
  scale_fill_manual("TF2",
                    labels = labvalues,
                    values = colvalues) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(colour = "black",
                                   angle = 45,
                                   hjust = 1),
        axis.text.y = element_text(colour = "black")) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 1]$fsm_eligible_percent_aut202021, probs = 0.50)), " (",
                                  round(quantile(spine[budget_2021_75 == 1]$fsm_eligible_percent_aut202021, probs = 0.25)), ", ",
                                  round(quantile(spine[budget_2021_75 == 1]$fsm_eligible_percent_aut202021, probs = 0.75)), ")"),
           x = 10, y = 30, size = 3) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 0]$fsm_eligible_percent_aut202021, probs = 0.50)), " (",
                                  round(quantile(spine[budget_2021_75 == 0]$fsm_eligible_percent_aut202021, probs = 0.25)), ", ",
                                  round(quantile(spine[budget_2021_75 == 0]$fsm_eligible_percent_aut202021, probs = 0.75)), ")"),
           x = 28, y = 30, size = 3)
```

```{r imd, fig.width = 10, fig.height = 7.5}
spine[, LAD21NM := factor(LAD21NM, levels = spine$LAD21NM[order(spine$budget_2021_75, spine$imd_10pc, decreasing = T)])]
spine[, budget_2021_75_tmp := as.character(budget_2021_75)]

namevals <- c("0", "1")
colvalues <- c("blue", "red")
labvalues <- c("No", "Yes")

names(colvalues) <- namevals
names(labvalues) <- namevals

ggplot(aes(x = LAD21NM,
           y = imd_10pc,
           fill = as.factor(budget_2021_75_tmp)),
       data = spine) +
  geom_bar(stat = "identity") +
  scale_y_continuous(name = "% LSOAs in most deprived decile nationally",
                     expand = c(0, 0),
                     limits = c(0, 15)) +
  scale_x_discrete(name = "") +
  labs(fill = "2021 Family Hub budget",
       title = "IMD 2019: percentage of LSOAs in the most deprived decile nationally") +
  scale_fill_manual("TF2",
                    labels = labvalues,
                    values = colvalues) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(colour = "black",
                                   angle = 45,
                                   hjust = 1),
        axis.text.y = element_text(colour = "black")) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 1]$imd_10pc, probs = 0.50)), " (",
                                  round(quantile(spine[budget_2021_75 == 1]$imd_10pc, probs = 0.25)), ", ",
                                  round(quantile(spine[budget_2021_75 == 1]$imd_10pc, probs = 0.75)), ")"),
           x = 10, y = 10, size = 3) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 0]$imd_10pc, probs = 0.50)), " (",
                                  round(quantile(spine[budget_2021_75 == 0]$imd_10pc, probs = 0.25)), ", ",
                                  round(quantile(spine[budget_2021_75 == 0]$imd_10pc, probs = 0.75)), ")"),
           x = 28, y = 10, size = 3)
```

```{r homelessness, fig.width = 10, fig.height = 7.5}
spine <- merge(spine,
               ftps[indicatorid == 93739, c("areacode", "value")],
               by.x = "LAD21C",
               by.y = "areacode")

setnames(spine, "value", "homeless")

spine[, LAD21NM := factor(LAD21NM, levels = spine$LAD21NM[order(spine$budget_2021_75, spine$homeless, decreasing = T)])]
spine[, budget_2021_75_tmp := as.character(budget_2021_75)]

namevals <- c("0", "1")
colvalues <- c("blue", "red")
labvalues <- c("No", "Yes")

names(colvalues) <- namevals
names(labvalues) <- namevals

ggplot(aes(x = LAD21NM,
           y = homeless,
           fill = as.factor(budget_2021_75_tmp)),
       data = spine) +
  geom_bar(stat = "identity") +
  scale_y_continuous(name = "Households owed duty rate per 1,000",
                     expand = c(0, 0),
                     limits = c(0, 40)) +
  scale_x_discrete(name = "") +
  labs(fill = "2021 Family Hub budget",
       title = "Households (applicant 16-24 yrs) owed homelessness duty, rate per 1,000") +
  scale_fill_manual("TF2",
                    labels = labvalues,
                    values = colvalues) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(colour = "black",
                                   angle = 45,
                                   hjust = 1),
        axis.text.y = element_text(colour = "black")) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 1]$homeless, probs = 0.50, na.rm = T)), " (",
                                  round(quantile(spine[budget_2021_75 == 1]$homeless, probs = 0.25, na.rm = T)), ", ",
                                  round(quantile(spine[budget_2021_75 == 1]$homeless, probs = 0.75, na.rm = T)), ") per 1,000"),
           x = 10, y = 30, size = 3) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 0]$homeless, probs = 0.50, na.rm = T)), " (",
                                  round(quantile(spine[budget_2021_75 == 0]$homeless, probs = 0.25, na.rm = T)), ", ",
                                  round(quantile(spine[budget_2021_75 == 0]$homeless, probs = 0.75, na.rm = T)), ") per 1,000"),
           x = 28, y = 30, size = 3)
```
Note: data not available on homelessness for Haringey, Hounslow or Tower Hamlets.

```{r low income, fig.width = 10, fig.height = 7.5}
spine <- merge(spine,
               ftps[indicatorid == 93700, c("areacode", "value")],
               by.x = "LAD21C",
               by.y = "areacode")

setnames(spine, "value", "low_income")

spine[, LAD21NM := factor(LAD21NM, levels = spine$LAD21NM[order(spine$budget_2021_75, spine$low_income, decreasing = T)])]
spine[, budget_2021_75_tmp := as.character(budget_2021_75)]

namevals <- c("0", "1")
colvalues <- c("blue", "red")
labvalues <- c("No", "Yes")

names(colvalues) <- namevals
names(labvalues) <- namevals

ggplot(aes(x = LAD21NM,
           y = low_income,
           fill = as.factor(budget_2021_75_tmp)),
       data = spine) +
  geom_bar(stat = "identity") +
  scale_y_continuous(name = "% low income",
                     expand = c(0, 0),
                     limits = c(0, 30)) +
  scale_x_discrete(name = "") +
  labs(fill = "2021 Family Hub budget",
       title = "Percentage of children in relative low income families") +
  scale_fill_manual("TF2",
                    labels = labvalues,
                    values = colvalues) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(colour = "black",
                                   angle = 45,
                                   hjust = 1),
        axis.text.y = element_text(colour = "black")) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 1]$low_income, probs = 0.50, na.rm = T)), " (",
                                  round(quantile(spine[budget_2021_75 == 1]$low_income, probs = 0.25, na.rm = T)), ", ",
                                  round(quantile(spine[budget_2021_75 == 1]$low_income, probs = 0.75, na.rm = T)), ")"),
           x = 10, y = 25, size = 3) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 0]$low_income, probs = 0.50, na.rm = T)), " (",
                                  round(quantile(spine[budget_2021_75 == 0]$low_income, probs = 0.25, na.rm = T)), ", ",
                                  round(quantile(spine[budget_2021_75 == 0]$low_income, probs = 0.75, na.rm = T)), ")"),
           x = 28, y = 25, size = 3)
```

# Children's services
```{r cin31mar, fig.width = 10, fig.height = 7.5}
spine[, LAD21NM := factor(LAD21NM, levels = spine$LAD21NM[order(spine$budget_2021_75, spine$cin_at31_episodes_2022_rate_10000, decreasing = T)])]
spine[, budget_2021_75_tmp := as.character(budget_2021_75)]

namevals <- c("0", "1")
colvalues <- c("blue", "red")
labvalues <- c("No", "Yes")

names(colvalues) <- namevals
names(labvalues) <- namevals

ggplot(aes(x = LAD21NM,
           y = cin_at31_episodes_2022_rate_10000,
           fill = as.factor(budget_2021_75_tmp)),
       data = spine) +
  geom_bar(stat = "identity") +
  scale_y_continuous(name = "Rate per 10,000",
                     expand = c(0, 0),
                     limits = c(0, 1600)) +
  scale_x_discrete(name = "") +
  labs(fill = "2021 Family Hub budget",
       title = "Children in need 31 Mar 2022 per 10,000") +
  scale_fill_manual("TF2",
                    labels = labvalues,
                    values = colvalues) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(colour = "black",
                                   angle = 45,
                                   hjust = 1),
        axis.text.y = element_text(colour = "black")) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 1]$cin_at31_episodes_2022_rate_10000, probs = 0.50, na.rm = T)), " (",
                                  round(quantile(spine[budget_2021_75 == 1]$cin_at31_episodes_2022_rate_10000, probs = 0.25, na.rm = T)), ", ",
                                  round(quantile(spine[budget_2021_75 == 1]$cin_at31_episodes_2022_rate_10000, probs = 0.75, na.rm = T)), ")"),
           x = 10, y = 1100, size = 3) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 0]$cin_at31_episodes_2022_rate_10000, probs = 0.50, na.rm = T)), " (",
                                  round(quantile(spine[budget_2021_75 == 0]$cin_at31_episodes_2022_rate_10000, probs = 0.25, na.rm = T)), ", ",
                                  round(quantile(spine[budget_2021_75 == 0]$cin_at31_episodes_2022_rate_10000, probs = 0.75, na.rm = T)), ")"),
           x = 28, y = 1100, size = 3)
```

```{r cinref, fig.width = 10, fig.height = 7.5}
spine[, LAD21NM := factor(LAD21NM, levels = spine$LAD21NM[order(spine$budget_2021_75, spine$cin_refs_202122_rate_10000, decreasing = T)])]
spine[, budget_2021_75_tmp := as.character(budget_2021_75)]

namevals <- c("0", "1")
colvalues <- c("blue", "red")
labvalues <- c("No", "Yes")

names(colvalues) <- namevals
names(labvalues) <- namevals

ggplot(aes(x = LAD21NM,
           y = cin_refs_202122_rate_10000,
           fill = as.factor(budget_2021_75_tmp)),
       data = spine) +
  geom_bar(stat = "identity") +
  scale_y_continuous(name = "Rate per 10,000",
                     expand = c(0, 0),
                     limits = c(0, 1000)) +
  scale_x_discrete(name = "") +
  labs(fill = "2021 Family Hub budget",
       title = "Children referred to CSC 2021/22 per 10,000") +
  scale_fill_manual("TF2",
                    labels = labvalues,
                    values = colvalues) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(colour = "black",
                                   angle = 45,
                                   hjust = 1),
        axis.text.y = element_text(colour = "black")) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 1]$cin_refs_202122_rate_10000, probs = 0.50, na.rm = T)), " (",
                                  round(quantile(spine[budget_2021_75 == 1]$cin_refs_202122_rate_10000, probs = 0.25, na.rm = T)), ", ",
                                  round(quantile(spine[budget_2021_75 == 1]$cin_refs_202122_rate_10000, probs = 0.75, na.rm = T)), ")"),
           x = 10, y = 800, size = 3) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 0]$cin_refs_202122_rate_10000, probs = 0.50, na.rm = T)), " (",
                                  round(quantile(spine[budget_2021_75 == 0]$cin_refs_202122_rate_10000, probs = 0.25, na.rm = T)), ", ",
                                  round(quantile(spine[budget_2021_75 == 0]$cin_refs_202122_rate_10000, probs = 0.75, na.rm = T)), ")"),
           x = 28, y = 800, size = 3)
```

```{r cla31mar, fig.width = 10, fig.height = 7.5}
spine[, LAD21NM := factor(LAD21NM, levels = spine$LAD21NM[order(spine$budget_2021_75, spine$cla_at31_2022_rate_10000, decreasing = T)])]
spine[, budget_2021_75_tmp := as.character(budget_2021_75)]

namevals <- c("0", "1")
colvalues <- c("blue", "red")
labvalues <- c("No", "Yes")

names(colvalues) <- namevals
names(labvalues) <- namevals

ggplot(aes(x = LAD21NM,
           y = cla_at31_2022_rate_10000,
           fill = as.factor(budget_2021_75_tmp)),
       data = spine) +
  geom_bar(stat = "identity") +
  scale_y_continuous(name = "Rate per 10,000",
                     expand = c(0, 0),
                     limits = c(0, 200)) +
  scale_x_discrete(name = "") +
  labs(fill = "2021 Family Hub budget",
       title = "Children looked after 31 Mar 2022 per 10,000") +
  scale_fill_manual("TF2",
                    labels = labvalues,
                    values = colvalues) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(colour = "black",
                                   angle = 45,
                                   hjust = 1),
        axis.text.y = element_text(colour = "black")) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 1]$cla_at31_2022_rate_10000, probs = 0.50, na.rm = T)), " (",
                                  round(quantile(spine[budget_2021_75 == 1]$cla_at31_2022_rate_10000, probs = 0.25, na.rm = T)), ", ",
                                  round(quantile(spine[budget_2021_75 == 1]$cla_at31_2022_rate_10000, probs = 0.75, na.rm = T)), ")"),
           x = 10, y = 150, size = 3) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 0]$cla_at31_2022_rate_10000, probs = 0.50, na.rm = T)), " (",
                                  round(quantile(spine[budget_2021_75 == 0]$cla_at31_2022_rate_10000, probs = 0.25, na.rm = T)), ", ",
                                  round(quantile(spine[budget_2021_75 == 0]$cla_at31_2022_rate_10000, probs = 0.75, na.rm = T)), ")"),
           x = 28, y = 150, size = 3)
```

```{r clastarts, fig.width = 10, fig.height = 7.5}
spine[, LAD21NM := factor(LAD21NM, levels = spine$LAD21NM[order(spine$budget_2021_75, spine$cla_starts_202122_rate_10000, decreasing = T)])]
spine[, budget_2021_75_tmp := as.character(budget_2021_75)]

namevals <- c("0", "1")
colvalues <- c("blue", "red")
labvalues <- c("No", "Yes")

names(colvalues) <- namevals
names(labvalues) <- namevals

ggplot(aes(x = LAD21NM,
           y = cla_starts_202122_rate_10000,
           fill = as.factor(budget_2021_75_tmp)),
       data = spine) +
  geom_bar(stat = "identity") +
  scale_y_continuous(name = "Rate per 10,000",
                     expand = c(0, 0),
                     limits = c(0, 150)) +
  scale_x_discrete(name = "") +
  labs(fill = "2021 Family Hub budget",
       title = "Children starting to be looked after 2021/22 per 10,000") +
  scale_fill_manual("TF2",
                    labels = labvalues,
                    values = colvalues) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(colour = "black",
                                   angle = 45,
                                   hjust = 1),
        axis.text.y = element_text(colour = "black")) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 1]$cla_starts_202122_rate_10000, probs = 0.50, na.rm = T)), " (",
                                  round(quantile(spine[budget_2021_75 == 1]$cla_starts_202122_rate_10000, probs = 0.25, na.rm = T)), ", ",
                                  round(quantile(spine[budget_2021_75 == 1]$cla_starts_202122_rate_10000, probs = 0.75, na.rm = T)), ")"),
           x = 10, y = 100, size = 3) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 0]$cla_starts_202122_rate_10000, probs = 0.50, na.rm = T)), " (",
                                  round(quantile(spine[budget_2021_75 == 0]$cla_starts_202122_rate_10000, probs = 0.25, na.rm = T)), ", ",
                                  round(quantile(spine[budget_2021_75 == 0]$cla_starts_202122_rate_10000, probs = 0.75, na.rm = T)), ")"),
           x = 28, y = 100, size = 3)
```

# Mental healh outcomes
```{r alcohol, fig.width = 10, fig.height = 7.5}
spine <- merge(spine,
               ftps[indicatorid == 92904, c("areacode", "value")],
               by.x = "LAD21C",
               by.y = "areacode")

setnames(spine, "value", "alcohol")

spine[, LAD21NM := factor(LAD21NM, levels = spine$LAD21NM[order(spine$budget_2021_75, spine$alcohol, decreasing = T)])]
spine[, budget_2021_75_tmp := as.character(budget_2021_75)]

namevals <- c("0", "1")
colvalues <- c("blue", "red")
labvalues <- c("No", "Yes")

names(colvalues) <- namevals
names(labvalues) <- namevals

ggplot(aes(x = LAD21NM,
           y = alcohol,
           fill = as.factor(budget_2021_75_tmp)),
       data = spine) +
  geom_bar(stat = "identity") +
  scale_y_continuous(name = "Rate per 100,000",
                     expand = c(0, 0),
                     limits = c(0, 40)) +
  scale_x_discrete(name = "") +
  labs(fill = "2021 Family Hub budget",
       title = "Alcohol-specific condition admissions <18 yrs, per 100,000") +
  scale_fill_manual("TF2",
                    labels = labvalues,
                    values = colvalues) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(colour = "black",
                                   angle = 45,
                                   hjust = 1),
        axis.text.y = element_text(colour = "black")) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 1]$alcohol, probs = 0.50, na.rm = T)), " (",
                                  round(quantile(spine[budget_2021_75 == 1]$alcohol, probs = 0.25, na.rm = T)), ", ",
                                  round(quantile(spine[budget_2021_75 == 1]$alcohol, probs = 0.75, na.rm = T)), ")"),
           x = 10, y = 25, size = 3) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 0]$alcohol, probs = 0.50, na.rm = T)), " (",
                                  round(quantile(spine[budget_2021_75 == 0]$alcohol, probs = 0.25, na.rm = T)), ", ",
                                  round(quantile(spine[budget_2021_75 == 0]$alcohol, probs = 0.75, na.rm = T)), ")"),
           x = 28, y = 25, size = 3)
```

```{r self-harm, fig.width = 10, fig.height = 7.5}
spine <- merge(spine,
               ftps[indicatorid == 90813, c("areacode", "value")],
               by.x = "LAD21C",
               by.y = "areacode")

setnames(spine, "value", "selfharm")

spine[, LAD21NM := factor(LAD21NM, levels = spine$LAD21NM[order(spine$budget_2021_75, spine$selfharm, decreasing = T)])]
spine[, budget_2021_75_tmp := as.character(budget_2021_75)]

namevals <- c("0", "1")
colvalues <- c("blue", "red")
labvalues <- c("No", "Yes")

names(colvalues) <- namevals
names(labvalues) <- namevals

ggplot(aes(x = LAD21NM,
           y = selfharm,
           fill = as.factor(budget_2021_75_tmp)),
       data = spine) +
  geom_bar(stat = "identity") +
  scale_y_continuous(name = "Rate per 100,000",
                     expand = c(0, 0),
                     limits = c(0, 600)) +
  scale_x_discrete(name = "") +
  labs(fill = "2021 Family Hub budget",
       title = "Self-harm admissions ages 10-24 yrs, per 100,000") +
  scale_fill_manual("TF2",
                    labels = labvalues,
                    values = colvalues) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(colour = "black",
                                   angle = 45,
                                   hjust = 1),
        axis.text.y = element_text(colour = "black")) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 1]$selfharm, probs = 0.50, na.rm = T)), " (",
                                  round(quantile(spine[budget_2021_75 == 1]$selfharm, probs = 0.25, na.rm = T)), ", ",
                                  round(quantile(spine[budget_2021_75 == 1]$selfharm, probs = 0.75, na.rm = T)), ")"),
           x = 10, y = 400, size = 3) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 0]$selfharm, probs = 0.50, na.rm = T)), " (",
                                  round(quantile(spine[budget_2021_75 == 0]$selfharm, probs = 0.25, na.rm = T)), ", ",
                                  round(quantile(spine[budget_2021_75 == 0]$selfharm, probs = 0.75, na.rm = T)), ")"),
           x = 28, y = 400, size = 3)
```

```{r substance, fig.width = 10, fig.height = 7.5}
spine <- merge(spine,
               ftps[indicatorid == 90808, c("areacode", "value")],
               by.x = "LAD21C",
               by.y = "areacode")

setnames(spine, "value", "substance")

spine[, LAD21NM := factor(LAD21NM, levels = spine$LAD21NM[order(spine$budget_2021_75, spine$substance, decreasing = T)])]
spine[, budget_2021_75_tmp := as.character(budget_2021_75)]

namevals <- c("0", "1")
colvalues <- c("blue", "red")
labvalues <- c("No", "Yes")

names(colvalues) <- namevals
names(labvalues) <- namevals

ggplot(aes(x = LAD21NM,
           y = substance,
           fill = as.factor(budget_2021_75_tmp)),
       data = spine) +
  geom_bar(stat = "identity") +
  scale_y_continuous(name = "Rate per 100,000",
                     expand = c(0, 0),
                     limits = c(0, 150)) +
  scale_x_discrete(name = "") +
  labs(fill = "2021 Family Hub budget",
       title = "Substance misuse admissions 15-24 yrs, per 100,000") +
  scale_fill_manual("TF2",
                    labels = labvalues,
                    values = colvalues) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(colour = "black",
                                   angle = 45,
                                   hjust = 1),
        axis.text.y = element_text(colour = "black")) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 1]$substance, probs = 0.50, na.rm = T)), " (",
                                  round(quantile(spine[budget_2021_75 == 1]$substance, probs = 0.25, na.rm = T)), ", ",
                                  round(quantile(spine[budget_2021_75 == 1]$substance, probs = 0.75, na.rm = T)), ")"),
           x = 10, y = 100, size = 3) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 0]$substance, probs = 0.50, na.rm = T)), " (",
                                  round(quantile(spine[budget_2021_75 == 0]$substance, probs = 0.25, na.rm = T)), ", ",
                                  round(quantile(spine[budget_2021_75 == 0]$substance, probs = 0.75, na.rm = T)), ")"),
           x = 28, y = 100, size = 3)
```

```{r mh, fig.width = 10, fig.height = 7.5}
spine <- merge(spine,
               ftps[indicatorid == 90812, c("areacode", "value")],
               by.x = "LAD21C",
               by.y = "areacode")

setnames(spine, "value", "mh")

spine[, LAD21NM := factor(LAD21NM, levels = spine$LAD21NM[order(spine$budget_2021_75, spine$mh, decreasing = T)])]
spine[, budget_2021_75_tmp := as.character(budget_2021_75)]

namevals <- c("0", "1")
colvalues <- c("blue", "red")
labvalues <- c("No", "Yes")

names(colvalues) <- namevals
names(labvalues) <- namevals

ggplot(aes(x = LAD21NM,
           y = mh,
           fill = as.factor(budget_2021_75_tmp)),
       data = spine) +
  geom_bar(stat = "identity") +
  scale_y_continuous(name = "Rate per 100,000",
                     expand = c(0, 0),
                     limits = c(0, 200)) +
  scale_x_discrete(name = "") +
  labs(fill = "2021 Family Hub budget",
       title = "Mental health conditions admissions < 18 yrs, per 100,000") +
  scale_fill_manual("TF2",
                    labels = labvalues,
                    values = colvalues) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(colour = "black",
                                   angle = 45,
                                   hjust = 1),
        axis.text.y = element_text(colour = "black")) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 1]$mh, probs = 0.50, na.rm = T)), " (",
                                  round(quantile(spine[budget_2021_75 == 1]$mh, probs = 0.25, na.rm = T)), ", ",
                                  round(quantile(spine[budget_2021_75 == 1]$mh, probs = 0.75, na.rm = T)), ")"),
           x = 10, y = 100, size = 3) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 0]$mh, probs = 0.50, na.rm = T)), " (",
                                  round(quantile(spine[budget_2021_75 == 0]$mh, probs = 0.25, na.rm = T)), ", ",
                                  round(quantile(spine[budget_2021_75 == 0]$mh, probs = 0.75, na.rm = T)), ")"),
           x = 28, y = 100, size = 3)
```

# SEN provision
```{r sensupport, fig.width = 10, fig.height = 7.5}
spine[, LAD21NM := factor(LAD21NM, levels = spine$LAD21NM[order(spine$budget_2021_75, spine$sen_support_percent202122, decreasing = T)])]
spine[, budget_2021_75_tmp := as.character(budget_2021_75)]

namevals <- c("0", "1")
colvalues <- c("blue", "red")
labvalues <- c("No", "Yes")

names(colvalues) <- namevals
names(labvalues) <- namevals

ggplot(aes(x = LAD21NM,
           y = sen_support_percent202122,
           fill = as.factor(budget_2021_75_tmp)),
       data = spine) +
  geom_bar(stat = "identity") +
  scale_y_continuous(name = "% children getting SEN support 2020/21",
                     expand = c(0, 0),
                     limits = c(0, 20)) +
  scale_x_discrete(name = "") +
  labs(fill = "2021 Family Hub budget",
       title = "Percentage of children getting SEN support in 2020/21") +
  scale_fill_manual("TF2",
                    labels = labvalues,
                    values = colvalues) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(colour = "black",
                                   angle = 45,
                                   hjust = 1),
        axis.text.y = element_text(colour = "black")) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 1]$sen_support_percent202122, probs = 0.50)), " (",
                                  round(quantile(spine[budget_2021_75 == 1]$sen_support_percent202122, probs = 0.25)), ", ",
                                  round(quantile(spine[budget_2021_75 == 1]$sen_support_percent202122, probs = 0.75)), ")"),
           x = 10, y = 17, size = 3) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 0]$sen_support_percent202122, probs = 0.50)), " (",
                                  round(quantile(spine[budget_2021_75 == 0]$sen_support_percent202122, probs = 0.25)), ", ",
                                  round(quantile(spine[budget_2021_75 == 0]$sen_support_percent202122, probs = 0.75)), ")"),
           x = 28, y = 17, size = 3)
```

```{r ehcp, fig.width = 10, fig.height = 7.5}
spine[, LAD21NM := factor(LAD21NM, levels = spine$LAD21NM[order(spine$budget_2021_75, spine$ehc_plan_percent202122, decreasing = T)])]
spine[, budget_2021_75_tmp := as.character(budget_2021_75)]

namevals <- c("0", "1")
colvalues <- c("blue", "red")
labvalues <- c("No", "Yes")

names(colvalues) <- namevals
names(labvalues) <- namevals

ggplot(aes(x = LAD21NM,
           y = ehc_plan_percent202122,
           fill = as.factor(budget_2021_75_tmp)),
       data = spine) +
  geom_bar(stat = "identity") +
  scale_y_continuous(name = "% children on EHCP 2020/21",
                     expand = c(0, 0),
                     limits = c(0, 10)) +
  scale_x_discrete(name = "") +
  labs(fill = "2021 Family Hub budget",
       title = "Percentage of children on EHCP in 2020/21") +
  scale_fill_manual("TF2",
                    labels = labvalues,
                    values = colvalues) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(colour = "black",
                                   angle = 45,
                                   hjust = 1),
        axis.text.y = element_text(colour = "black")) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 1]$ehc_plan_percent202122, probs = 0.50)), " (",
                                  round(quantile(spine[budget_2021_75 == 1]$ehc_plan_percent202122, probs = 0.25)), ", ",
                                  round(quantile(spine[budget_2021_75 == 1]$ehc_plan_percent202122, probs = 0.75)), ")"),
           x = 10, y = 7, size = 3) +
  annotate("text", label = paste0("Median (IQR):\n",
                                  round(quantile(spine[budget_2021_75 == 0]$ehc_plan_percent202122, probs = 0.50)), " (",
                                  round(quantile(spine[budget_2021_75 == 0]$ehc_plan_percent202122, probs = 0.25)), ", ",
                                  round(quantile(spine[budget_2021_75 == 0]$ehc_plan_percent202122, probs = 0.75)), ")"),
           x = 28, y = 7, size = 3)
```
